In [10]:
from numpy import exp, array, random, dot


class NeuralNetwork():
    def setup(self, input_n):
        print(input_n)
        # Seed the random number generator, so it generates the same numbers
        # every time the program runs.
        random.seed(1)

        # We model a single neuron, with 3 input connections and 1 output connection.
        # We assign random weights to a 3 x 1 matrix, with values in the range -1 to 1
        # and mean 0.
        self.synaptic_weights = 2 * random.random((input_n, 1)) - 1

    # The Sigmoid function, which describes an S shaped curve.
    # We pass the weighted sum of the inputs through this function to
    # normalise them between 0 and 1.
    def __sigmoid(self, x):
        return 1 / (1 + exp(-x))

    # The derivative of the Sigmoid function.
    # This is the gradient of the Sigmoid curve.
    # It indicates how confident we are about the existing weight.
    def __sigmoid_derivative(self, x):
        return x * (1 - x)

    # We train the neural network through a process of trial and error.
    # Adjusting the synaptic weights each time.
    def train(self, training_set_inputs, training_set_outputs, number_of_training_iterations):
        self.setup(len(training_set_inputs[0]))
        for iteration in range(number_of_training_iterations):
            # Pass the training set through our neural network (a single neuron).
            output = self.think(training_set_inputs)

            # Calculate the error (The difference between the desired output
            # and the predicted output).
            error = training_set_outputs - output

            # Multiply the error by the input and again by the gradient of the Sigmoid curve.
            # This means less confident weights are adjusted more.
            # This means inputs, which are zero, do not cause changes to the weights.
            adjustment = dot(training_set_inputs.T, error * self.__sigmoid_derivative(output))

            # Adjust the weights.
            self.synaptic_weights += adjustment

    # The neural network thinks.
    def think(self, inputs):
        # Pass inputs through our neural network (our single neuron).
        return self.__sigmoid(dot(inputs, self.synaptic_weights))


if __name__ == "__main__":

    #Intialise a single neuron neural network.
    neural_network = NeuralNetwork()

    print ("Random starting synaptic weights: ")
    # print (neural_network.synaptic_weights)

    # The training set. We have 4 examples, each consisting of 3 input values
    # and 1 output value.
    training_set_inputs = array([[0, 0, 1], [1, 1, 1], [1, 0, 1], [0, 1, 1]])
    training_set_outputs = array([[0, 1, 1, 0]]).T

    # Train the neural network using a training set.
    # Do it 10,000 times and make small adjustments each time.
    neural_network.train(training_set_inputs, training_set_outputs, 10000)

    print ("New synaptic weights after training: ")
    print (neural_network.synaptic_weights)

    # Test the neural network with a new situation.
    print ("Considering new situation [1, 0, 0] -> ?: ")
    print (neural_network.think(array([1, 0, 0])))

Random starting synaptic weights: 
3
New synaptic weights after training: 
[[ 9.67299303]
 [-0.2078435 ]
 [-4.62963669]]
Considering new situation [1, 0, 0] -> ?: 
[0.99993704]


In [4]:
import pandas as pd
chicago_taxi_dataset = pd.read_csv("https://download.mlcc.google.com/mledu-datasets/chicago_taxi_train.csv")

In [18]:
neural_network = NeuralNetwork()

print ("Random starting synaptic weights: ")

sample_set = chicago_taxi_dataset.sample(frac=0.1)
sample_set = sample_set.fillna(0)

training_set_inputs = sample_set.iloc[:, 5:7].values
training_set_outputs = sample_set.iloc[:, 11:12].values
print(training_set_inputs)
# Train the neural network using a training set.
# Do it 10,000 times and make small adjustments each time.
neural_network.train(training_set_inputs, training_set_outputs, 5)

print ("New synaptic weights after training: ")
print (neural_network.synaptic_weights)

# Test the neural network with a new situation.
test_row = chicago_taxi_dataset.sample(n=1)
test_row = test_row.fillna(0)
test_input = test_row.iloc[:, 5:7].values
print(test_input)
print (f"Considering new situation {test_input} -> ?: ")

print (neural_network.think(test_input))

Random starting synaptic weights: 
[[1.39000000e+01 0.00000000e+00]
 [3.69000000e+01 1.70319801e+10]
 [2.09000000e+01 0.00000000e+00]
 ...
 [4.16000000e+01 1.70319800e+10]
 [2.96000000e+01 0.00000000e+00]
 [1.41000000e+01 0.00000000e+00]]
2
New synaptic weights after training: 
[[2.32098857e+03]
 [4.40648987e-01]]
[[40.3  0. ]]
Considering new situation [[40.3  0. ]] -> ?: 
[[1.]]
